import type { Usuario } from '../types';

// ====================================================================
// 22 usuarios precargados. Las contraseñas están CIFRADAS (bcrypt): el
// texto plano NO aparece en el código. Generado por scripts/gen-hashes.mjs.
// Se cargan solo en el primer arranque (si la tabla usuarios está vacía).
// Los no-admin deben cambiar su clave en el primer login.
// ====================================================================
export const USUARIOS_SEED: Usuario[] = [
  { id: 'admin1', username: 'admin1', password: '$2a$10$pPoqeXt4pMIyfGU7096Qm.pyPs3yw2iPYA3L803ipxh/ebZYCr5/a', nombre_completo: 'Administrador Principal', rol: 'admin', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'admin2', username: 'admin2', password: '$2a$10$Q0IayRx5zgzCUoQtK4s.AOZpaSE0leJG9BteZMpv/8W0/531.ascy', nombre_completo: 'Administrador Secundario', rol: 'admin', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR1_1', username: 'VendedorR1_1', password: '$2a$10$msmrmYm5rl9KEMNQ0Ct9reZZDzKmIkcK6bbuDmMa4y9Jo5C8xHG6a', nombre_completo: 'Vendedor 1 Ruta 1', rol: 'vendedor', ruta_asignada: 'Ruta 1 (Zona Oeste/Norte)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR1_2', username: 'VendedorR1_2', password: '$2a$10$y/jaT6etuc.luQ2WIEXOx.3pcRVx87AR.52UXwdf6qbE/ZP8YEFs6', nombre_completo: 'Vendedor 2 Ruta 1', rol: 'vendedor', ruta_asignada: 'Ruta 1 (Zona Oeste/Norte)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR2_3', username: 'VendedorR2_3', password: '$2a$10$s6fAmO5IlyXFiJK8m7iN4ueIGAn0I0iROHSAQZ.xLdpoaYJODXw7G', nombre_completo: 'Vendedor 3 Ruta 2', rol: 'vendedor', ruta_asignada: 'Ruta 2 (Zona Centro/Sur)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR2_4', username: 'VendedorR2_4', password: '$2a$10$ovx5ZSWUXy296KtHS5kyhO0S4b8UdcvB8/Z60hsepPJjVV.YhB.xW', nombre_completo: 'Vendedor 4 Ruta 2', rol: 'vendedor', ruta_asignada: 'Ruta 2 (Zona Centro/Sur)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR3_5', username: 'VendedorR3_5', password: '$2a$10$7GD6sCL6rx1o3rbKaw.GuuTc7doKO3KzdFe2vm19lG4ZkqylYlq6K', nombre_completo: 'Vendedor 5 Ruta 3', rol: 'vendedor', ruta_asignada: 'Ruta 3 (Zona Este)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR3_6', username: 'VendedorR3_6', password: '$2a$10$gnGb2b3yLww8MrAbH.rGB.iV4Y24x4fMVGualffNI1.sCflOmpPfW', nombre_completo: 'Vendedor 6 Ruta 3', rol: 'vendedor', ruta_asignada: 'Ruta 3 (Zona Este)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR1_7', username: 'VendedorR1_7', password: '$2a$10$RkvHpzmi77VTJc95T3gYg.42HMRGjBX5tbSYdwmmOwbAtzXBpZ3.a', nombre_completo: 'Vendedor 7 Ruta 1', rol: 'vendedor', ruta_asignada: 'Ruta 1 (Zona Oeste/Norte)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR2_8', username: 'VendedorR2_8', password: '$2a$10$YW.kr3/qainqiUKPe7EDsOPM9sCRTtyr/OpiakNjQmO8jYNDExXMq', nombre_completo: 'Vendedor 8 Ruta 2', rol: 'vendedor', ruta_asignada: 'Ruta 2 (Zona Centro/Sur)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR3_9', username: 'VendedorR3_9', password: '$2a$10$VnwraYSJIaA5iH8o9yM2b.SG6bdM71TFuNUcGO1vBkc4UEHyy3C82', nombre_completo: 'Vendedor 9 Ruta 3', rol: 'vendedor', ruta_asignada: 'Ruta 3 (Zona Este)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR1_10', username: 'VendedorR1_10', password: '$2a$10$ZZr1dhP1QhZd2IT3/UCg0OLkXJK1BNQUI8xA3c9fvKVX7XAvDeX56', nombre_completo: 'Vendedor 10 Ruta 1', rol: 'vendedor', ruta_asignada: 'Ruta 1 (Zona Oeste/Norte)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Despachador1', username: 'Despachador1', password: '$2a$10$0ukxzlLyKo54MbQ7dHjm3.NqJnG2.jZvYtscF/.VoZjlJrCvPKE0W', nombre_completo: 'Despachador 1', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Despachador2', username: 'Despachador2', password: '$2a$10$9T1p.aL0mXZa48GJtlPrY.eMMxQbu3gm.Tj94I/A485FXpU/u8iVu', nombre_completo: 'Despachador 2', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Despachador3', username: 'Despachador3', password: '$2a$10$spKASwUg50jxqwErAHBT5um5AmfN7Pz2.ccz.1IODcSKKlAUKl8w.', nombre_completo: 'Despachador 3', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Despachador4', username: 'Despachador4', password: '$2a$10$Wp0GnjqVG8zhli75/1277uEjtaZao4NoNNLRoj9.1xwTDQNfvIzIG', nombre_completo: 'Despachador 4', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Despachador5', username: 'Despachador5', password: '$2a$10$KxXSBx1GLFTCQ1JFsU/a3OoWdzXc5E21bFqaprQcwrigBoHn5Mp0.', nombre_completo: 'Despachador 5', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Almacenista1', username: 'Almacenista1', password: '$2a$10$5DACSYiCKrwob.tfrd41uury9B/GBXOEyaZLB1ywd76xes.Rew12a', nombre_completo: 'Almacenista 1', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Almacenista2', username: 'Almacenista2', password: '$2a$10$fLAhO4OgicP5dwvRzHrQbeuZUrbrUQjD1G8eBupAs/TJvXD3HL5/i', nombre_completo: 'Almacenista 2', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Almacenista3', username: 'Almacenista3', password: '$2a$10$S8daMhzDueJfls3ej4SMw.JMrHGJAOMzzH3zBWbjL3PFtDbHyzdYi', nombre_completo: 'Almacenista 3', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Almacenista4', username: 'Almacenista4', password: '$2a$10$Ik9dE8tBAZj3s32bkocPF.kE/M/LMTpRRnsDjP3JCrbR4kzMGHtei', nombre_completo: 'Almacenista 4', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Almacenista5', username: 'Almacenista5', password: '$2a$10$AEOJL.WmpmH3j/DiGzcgj.82gatoaSUuYg7zb.G.SQtqZsti1Jupy', nombre_completo: 'Almacenista 5', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
];
