import type { Usuario } from '../types';

// ====================================================================
// 22 usuarios precargados. Las contraseñas están CIFRADAS (bcrypt): el
// texto plano NO aparece en el código. Generado por scripts/gen-hashes.mjs.
// Se cargan solo en el primer arranque (si la tabla usuarios está vacía).
// Los no-admin deben cambiar su clave en el primer login.
// ====================================================================
export const USUARIOS_SEED: Usuario[] = [
  { id: 'admin1', username: 'admin1', password: '$2a$10$yhFl3WY0MBs4v8xZASpaUOmk3lRyqWN2NBGX2SAcY7assGh0zgYEi', nombre_completo: 'Administrador Principal', rol: 'admin', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'admin2', username: 'admin2', password: '$2a$10$Su9kWr/YdpZfP/ynNEBtH.dyxNqm/JqjJ4c0b.k9sPePtwgqbkl2K', nombre_completo: 'Administrador Secundario', rol: 'admin', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR1_1', username: 'VendedorR1_1', password: '$2a$10$E38jGn7m0jlWhDv.1JEJ3ekuolJvmgbQx2wOUXgzOW5oO/AtRQZNa', nombre_completo: 'Vendedor 1 Ruta 1', rol: 'vendedor', ruta_asignada: 'Ruta 1 (Zona Oeste/Norte)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'VendedorR1_2', username: 'VendedorR1_2', password: '$2a$10$Y3xzZdThsyALwdmWbjl9HeeCQygQTnGMfxVj8B/cKy4AMaXR6Lgae', nombre_completo: 'Vendedor 2 Ruta 1', rol: 'vendedor', ruta_asignada: 'Ruta 1 (Zona Oeste/Norte)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'VendedorR2_3', username: 'VendedorR2_3', password: '$2a$10$vNrXvRgS6oHBFlPR3JXhBOGSa1MsfagyjqulBPNr392Dxe4Ohp7Aq', nombre_completo: 'Vendedor 3 Ruta 2', rol: 'vendedor', ruta_asignada: 'Ruta 2 (Zona Centro/Sur)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'VendedorR2_4', username: 'VendedorR2_4', password: '$2a$10$iUfH8gdcpDY.wvN/mXx6DOO1Gj4RB0MyvFrcwe2ISfseQbervEvJe', nombre_completo: 'Vendedor 4 Ruta 2', rol: 'vendedor', ruta_asignada: 'Ruta 2 (Zona Centro/Sur)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'VendedorR3_5', username: 'VendedorR3_5', password: '$2a$10$FtmKyI3IGVaYORozzU7PSOTCmmPJB/dPXJnKSQ61Lkb6E5GRGF4LC', nombre_completo: 'Vendedor 5 Ruta 3', rol: 'vendedor', ruta_asignada: 'Ruta 3 (Zona Este)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'VendedorR3_6', username: 'VendedorR3_6', password: '$2a$10$LEzgTWSIbaEj8hWu4pqo0elOLhYTGZlK.7/ok5PRcmjmkaAPLDA4a', nombre_completo: 'Vendedor 6 Ruta 3', rol: 'vendedor', ruta_asignada: 'Ruta 3 (Zona Este)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'VendedorR1_7', username: 'VendedorR1_7', password: '$2a$10$C5mOMTWGrZ865WRG7GMDr.YgY7KmhQSxepRx7XVaSOJd6L/58TYLW', nombre_completo: 'Vendedor 7 Ruta 1', rol: 'vendedor', ruta_asignada: 'Ruta 1 (Zona Oeste/Norte)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'VendedorR2_8', username: 'VendedorR2_8', password: '$2a$10$V.OUEUmE2ol5.lIVU60Xo.a0whMmR2hTVTF1G19RK/afcUGvHrLOq', nombre_completo: 'Vendedor 8 Ruta 2', rol: 'vendedor', ruta_asignada: 'Ruta 2 (Zona Centro/Sur)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'VendedorR3_9', username: 'VendedorR3_9', password: '$2a$10$f616wFn6Q8bb9KCOY27P4.rlxFC1iqA54sgq7VAdO/TcFdA47s9r6', nombre_completo: 'Vendedor 9 Ruta 3', rol: 'vendedor', ruta_asignada: 'Ruta 3 (Zona Este)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'VendedorR1_10', username: 'VendedorR1_10', password: '$2a$10$ywQiGZqwuhWKn71ClZ8NrOVVIWeArn/CcaVaE1WcBdDK91RU1BKEK', nombre_completo: 'Vendedor 10 Ruta 1', rol: 'vendedor', ruta_asignada: 'Ruta 1 (Zona Oeste/Norte)', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'Despachador1', username: 'Despachador1', password: '$2a$10$rzDqUvMvgt61n4qqv9BEsOSOx716E1VzvcjzkU7dfVkBSPhJ1/Ngm', nombre_completo: 'Despachador 1', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'Despachador2', username: 'Despachador2', password: '$2a$10$8tWZzhoVGGlsJdF/VPniT.d5vwQxqX8yHpjaocCA/h2N0E2itSthG', nombre_completo: 'Despachador 2', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'Despachador3', username: 'Despachador3', password: '$2a$10$QwgBPSuQpYeizVjBE1jD8enk2K/uDGcNxq4/6U56GZmxM8VJVor8a', nombre_completo: 'Despachador 3', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'Despachador4', username: 'Despachador4', password: '$2a$10$y7NbdTX/NpWCXXmYTt9im.DuTk4KfffjtNv5oNN4gJaMJ.8eMs/DS', nombre_completo: 'Despachador 4', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'Despachador5', username: 'Despachador5', password: '$2a$10$Ow0NE6a3WSgty6HGqElo5Ozd883jxLlk2lhjxpaE66aGHrPpi7G0a', nombre_completo: 'Despachador 5', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'Almacenista1', username: 'Almacenista1', password: '$2a$10$bajMP8O8bhodljfZ7sS60ON7nkRRjZukTosB5J8sajSXHFh4qfY5u', nombre_completo: 'Almacenista 1', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'Almacenista2', username: 'Almacenista2', password: '$2a$10$NaS594cvUbmFKVCdukYU3eDFJnaZ.F0o8NsnS5pRObd2b/K4glZ1K', nombre_completo: 'Almacenista 2', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'Almacenista3', username: 'Almacenista3', password: '$2a$10$p2CdE/FeLrKkhzdi9DnhDOzkp2wh1SfEPTUXHWkmjCJHWqim7anKu', nombre_completo: 'Almacenista 3', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'Almacenista4', username: 'Almacenista4', password: '$2a$10$DKCnIjcbnMpLXvX8N00XTee/pprMDGlK4wJ7bCnW6FvQ0scFQAAt6', nombre_completo: 'Almacenista 4', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
  { id: 'Almacenista5', username: 'Almacenista5', password: '$2a$10$ZuQ2PfGRhNDQ3KcuNqEpxObuAbjqOZhoiIka0Ip3BnfauvjemFxaW', nombre_completo: 'Almacenista 5', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: true },
];
