import type { Usuario } from '../types';

// ====================================================================
// 22 usuarios precargados. Las contraseñas están CIFRADAS (bcrypt): el
// texto plano NO aparece en el código. Generado por scripts/gen-hashes.mjs.
// Se cargan solo en el primer arranque (si la tabla usuarios está vacía).
// Los no-admin deben cambiar su clave en el primer login.
// ====================================================================
export const USUARIOS_SEED: Usuario[] = [
  { id: 'admin1', username: 'admin1', password: '$2a$10$2HYA01c8b8anGtUKzPIZ0uZkaNUHotrykyezynzXWc5yGd.EJELqe', nombre_completo: 'Administrador Principal', rol: 'admin', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'admin2', username: 'admin2', password: '$2a$10$M.W3E2/bcaYvvLC.29zfsuEKKrYtexVb8pMfqc05uy2tZK223giSa', nombre_completo: 'Administrador Secundario', rol: 'admin', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR1_1', username: 'VendedorR1_1', password: '$2a$10$GSSQ/FNQWroFEl/O2tNt5.sQI1yQEvbx.Ky6cyANA8BkI/pB5vn/q', nombre_completo: 'Vendedor 1 Ruta 1', rol: 'vendedor', ruta_asignada: 'Catia 1', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR1_2', username: 'VendedorR1_2', password: '$2a$10$B3Ce6DR4u7v0AFeL4DpaoeydvTy07cZcgk0d22bemtThJ/d1tgXXS', nombre_completo: 'Vendedor 2 Ruta 1', rol: 'vendedor', ruta_asignada: 'Catia 2', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR2_3', username: 'VendedorR2_3', password: '$2a$10$vi60tVc6QVzdXUCkQeVsqO4rE78QafGYiFeH/xdvx43r0ijvIudqu', nombre_completo: 'Vendedor 3 Ruta 2', rol: 'vendedor', ruta_asignada: 'El Paraíso 1', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR2_4', username: 'VendedorR2_4', password: '$2a$10$b2ttq20apavjDeHtm9jrLeYh/aPUAKayUCrnbWeyQfMtIy4g1stNe', nombre_completo: 'Vendedor 4 Ruta 2', rol: 'vendedor', ruta_asignada: 'El Paraíso 2', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR3_5', username: 'VendedorR3_5', password: '$2a$10$7yeg76Mf2bc27vvnUslQNOg5Rs90809fut88.YJdS0t/sovYC9IH6', nombre_completo: 'Vendedor 5 Ruta 3', rol: 'vendedor', ruta_asignada: 'Quinta Crespo 1', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR3_6', username: 'VendedorR3_6', password: '$2a$10$qdYP3OD27JQKsfhYWuLSbOVWMzQkeQfrW3xhwlkVNoJORUlVmZgHW', nombre_completo: 'Vendedor 6 Ruta 3', rol: 'vendedor', ruta_asignada: 'Quinta Crespo 2', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR1_7', username: 'VendedorR1_7', password: '$2a$10$HG.VFwM.x51sCpzurCDA9eop1JdD9FreP0fnqKm4Uxhe2.dtUJfT.', nombre_completo: 'Vendedor 7 Ruta 1', rol: 'vendedor', ruta_asignada: 'Catia 1', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR2_8', username: 'VendedorR2_8', password: '$2a$10$AA3OesI61Cjd1zaM3onfFe/Gys9XYIR7SeTBg/xDyZJwFKRDhiBKK', nombre_completo: 'Vendedor 8 Ruta 2', rol: 'vendedor', ruta_asignada: 'El Paraíso 1', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR3_9', username: 'VendedorR3_9', password: '$2a$10$0DSg701LI/JGLSuvZVtu0e5Mgx3VDJrUgE/uhpVHogoyC5yDNuwry', nombre_completo: 'Vendedor 9 Ruta 3', rol: 'vendedor', ruta_asignada: 'Quinta Crespo 1', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'VendedorR1_10', username: 'VendedorR1_10', password: '$2a$10$i2jICHjz6c32Kz1rmw8xI.elQuTT1jfH2t6fKP3og5GzbwOe1rQCG', nombre_completo: 'Vendedor 10 Ruta 1', rol: 'vendedor', ruta_asignada: 'Catia 2', activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Despachador1', username: 'Despachador1', password: '$2a$10$Rq960cHiOvBtL7M2ovD5per7oGDemEDkGJBoHfjtVH24Me7qUfXIe', nombre_completo: 'Despachador 1', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Despachador2', username: 'Despachador2', password: '$2a$10$gTTyoxg19rNXKbp1ib7rYOJ84a33q5aHTCm3LKTXXZK1vYeUHJZwu', nombre_completo: 'Despachador 2', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Despachador3', username: 'Despachador3', password: '$2a$10$.WbNsnp9upufpk004JgEbuOvvzfe3kFjnK6X1RfdT6JFy9MecsANC', nombre_completo: 'Despachador 3', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Despachador4', username: 'Despachador4', password: '$2a$10$/./NSd6b2NdzQjfk5JhFM.tyLfexfNgJSBjCzvIKvtTtKE1LIbqVe', nombre_completo: 'Despachador 4', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Despachador5', username: 'Despachador5', password: '$2a$10$HC3dhHTqP63/3BjMmyZFo.kAVFohLAAzoCukjer1rpJeqgWPzBsPy', nombre_completo: 'Despachador 5', rol: 'despachador', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Almacenista1', username: 'Almacenista1', password: '$2a$10$4YCcUZs6xGuzKVKcz2Iam.KaiIWDkudbSOVuCqYXb6tkiBE0cCvnu', nombre_completo: 'Almacenista 1', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Almacenista2', username: 'Almacenista2', password: '$2a$10$gqSg/UPdWSnguijEyHh21uidbQehFbfhFLPtTwgiUJ.Rt4EhJRSEa', nombre_completo: 'Almacenista 2', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Almacenista3', username: 'Almacenista3', password: '$2a$10$NHVkWB.FI6nFCZgl9JcAduP5v5SJt1gA9ReidB3uLBiLJCCwMwZZW', nombre_completo: 'Almacenista 3', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Almacenista4', username: 'Almacenista4', password: '$2a$10$XrSVrgGBDRGwij.ZQqx30ull9rSrFxKWeR.agZyyl.41r5aNcDR2S', nombre_completo: 'Almacenista 4', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Almacenista5', username: 'Almacenista5', password: '$2a$10$Jd0DNy3HwKy/Bsv30O9gIOtZg3TQhievxL/2sxWnCifRI8nN5l2nS', nombre_completo: 'Almacenista 5', rol: 'almacenista', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Inventario1', username: 'Inventario1', password: '$2a$10$IS3D4agSpfFicfQHiYdIS.nkJl2aQBD8lMjFxQ8f9AA1i2sL3ggU2', nombre_completo: 'Analista de Inventario 1', rol: 'inventario', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
  { id: 'Inventario2', username: 'Inventario2', password: '$2a$10$M/rrIepaEnQROlp3PG0pSO2jPgFKxenFIhFBO85NJoywc23cFjk.S', nombre_completo: 'Analista de Inventario 2', rol: 'inventario', ruta_asignada: undefined, activo: true, fecha_creacion: '2026-01-01T00:00:00.000Z', creado_por: 'sistema', debe_cambiar_clave: false },
];
